- name: Install maven
  hosts: webservers
  become: yes
  tasks:
  - name: update-servers
    apt:  
     update_cache: true
     cache_valid_time: 3600
     force_apt_get: true
  - name: webserver-installation
    apt:
      name={{item}}
      state=present
    with_items:
    - openjdk-11-jdk
    - maven
