- name: Install mysql
  hosts: webservers
  become: yes
  tasks:
  - name: MySQL
    apt: 
      name={{item}} 
      state=present
    with_items:
    - mysql-server
    - MySQL-python3
    - libselinux-python3
    - libsemanage-python3
      
